CREATE TABLE [dbo].[USER] (
  [ID] numeric(15, 0) IDENTITY(1, 1) NOT NULL,
  [USERNAME] varchar(100) COLLATE Hungarian_CI_AS NOT NULL,
  [PASSWORD] varchar(255) COLLATE Hungarian_CI_AS NOT NULL,
  [EMAIL] varchar(100) COLLATE Hungarian_CI_AS,
  [MODIFY_BY] numeric(15, 0) NULL,
  [MODIFY_DATE] datetime NULL,
  [CREATE_BY] numeric(15, 0) NULL,
  [CREATE_DATE] datetime NULL,
  [STATE] varchar(1) COLLATE Hungarian_CI_AS NOT NULL,
  CONSTRAINT [PK_USERID] PRIMARY KEY NONCLUSTERED ([ID])
)
ON [PRIMARY]
GO