CREATE TABLE [dbo].[SUM_TAG_CONN] (
  [ID] numeric(15, 0) IDENTITY(1, 1) NOT NULL,
  [SUM_ID] numeric(15, 0) NOT NULL,
  [TAG_ID] numeric(15, 0) NOT NULL,
  [CREATE_BY] numeric(15, 0) NULL,
  [CREATE_DATE] datetime NULL,
  [STATE] varchar(1) COLLATE Hungarian_CI_AS NOT NULL,
  CONSTRAINT [PK_SUMTAGCONNID] PRIMARY KEY NONCLUSTERED ([ID]),
  CONSTRAINT [FK_SUMID] FOREIGN KEY ([SUM_ID]) 
	  REFERENCES [dbo].[SUM] ([ID]) 
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION,
  CONSTRAINT [FK_TAGID] FOREIGN KEY ([TAG_ID]) 
	  REFERENCES [dbo].[TAG] ([ID]) 
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION,
)
ON [PRIMARY]
GO