CREATE TABLE [dbo].[OPTION] (
  [ID] numeric(15, 0) IDENTITY(1, 1) NOT NULL,
  [OWNER_ID] numeric(15, 0) NOT NULL,
  [TITLE] varchar(255) COLLATE Hungarian_CI_AS NULL,
  [IS_ACTIVE] bit default 1 NULL,
  [STARTING_SUM] numeric(15, 0) NULL,
  [STARTING_DATE] datetime NULL,
  [MASTER_DATE_FROM] datetime NULL,
  [MASTER_DATE_TO] datetime NULL,
  [GRAPHVIEW_DATE_FROM] datetime NULL,
  [GRAPHVIEW_DATE_TO] datetime NULL,
  [PERIODAVERAGES_DATE_FROM] datetime NULL,
  [PERIODAVERAGES_DATE_TO] datetime NULL,
  [MONTHLYAVERAGES_DATE_FROM] datetime NULL,
  [MONTHLYAVERAGES_DATE_TO] datetime NULL,
  
  [MODIFY_BY] numeric(15, 0) NULL,
  [MODIFY_DATE] datetime NULL,
  [CREATE_BY] numeric(15, 0) NULL,
  [CREATE_DATE] datetime NULL,
  [STATE] varchar(1) COLLATE Hungarian_CI_AS NOT NULL,
  
  CONSTRAINT [PK_OPTIONID] PRIMARY KEY NONCLUSTERED ([ID]),
  CONSTRAINT [FK_OWNERID] FOREIGN KEY ([OWNER_ID]) 
	  REFERENCES [dbo].[USER] ([ID]) 
	  ON UPDATE NO ACTION
	  ON DELETE NO ACTION
)
ON [PRIMARY]
GO